version: '3.1'

services:
  mysql-container:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: wetro
      MYSQL_PASSWORD: 12341234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      --default-authentication-plugin=mysql_native_password
