version: "3"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wetro

      MYSQL_USER: wetro
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./docker/mysql/config:/etc/mysql/conf.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql